### ISSUE TITLE
Cannot find module 'caniuse-lite' 

### ISSUE THREAD

**Issue by An0nymous0** [ben-eb/caniuse-lite#10]
├─ caniuse-lite@1.0.30000712

error:
Module build failed: Error: Cannot find module 'caniuse-lite' (While processing preset: "/usr/local/openresty/nginx/html/study-manage/node_modules/babel-preset-env/lib/index.js")
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/openresty/nginx/html/study-manage/node_modules/babel-preset-env/node_modules/browserslist/index.js:5:15)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/openresty/nginx/html/study-manage/node_modules/babel-preset-env/lib/targets-parser.js:5:21)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/openresty/nginx/html/study-manage/node_modules/babel-preset-env/lib/index.js:33:22)
    at Module._compile (module.js:569:30)
 @ multi babel-polyfill ./src/main.js[39m[22m

demotion ： "caniuse-lite": "1.0.30000697",  
restore

**Comment by andyjansson** [comment]
Can you provide more information? I can install and reference the package just fine.

**Comment by An0nymous0** [comment]
@andyjansson  demo link : https://github.com/An0nymous0/error-demo

**Comment by andyjansson** [comment]
I couldn't reproduce the issue: 

```
C:\Users\Andy\Desktop\error-demo-master>yarn install
yarn install v0.27.5
[1/5] Resolving packages...
[2/5] Fetching packages...
warning fsevents@1.1.2: The platform "win32" is incompatible with this module.
info "fsevents@1.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/5] Linking dependencies...
[4/5] Building fresh packages...
[5/5] Cleaning modules...
Done in 94.24s.

C:\Users\Andy\Desktop\error-demo-master>yarn run build
yarn run v0.27.5
$ node build/build.js
Hash: 2d7698a6cf26c811c3ef
Version: webpack 3.5.1
Time: 2773ms
                                         Asset       Size  Chunks             Chunk Names
      static/js/vendor.0c24029043b82111ad31.js    83.3 kB       0  [emitted]  vendor
         static/js/app.2c3bccc3e8e1399583cb.js  523 bytes       1  [emitted]  app
    static/js/manifest.d679f9b029d67708102a.js    1.49 kB       2  [emitted]  manifest
  static/js/vendor.0c24029043b82111ad31.js.map     692 kB       0  [emitted]  vendor
     static/js/app.2c3bccc3e8e1399583cb.js.map    5.28 kB       1  [emitted]  app
static/js/manifest.d679f9b029d67708102a.js.map    14.2 kB       2  [emitted]  manifest
                                    index.html  381 bytes          [emitted]

  Build complete.

  Tip: built files are meant to be served over an HTTP server.
  Opening index.html over file:// won't work.

Done in 4.76s.
```

**Comment by An0nymous0** [comment]
@andyjansson 我尝试过用同样的环境模仿，另一个系统同样无法重现。我尝试过删除node_models,和清除npm cache，但我确定是升级后的问题。

**Comment by andyjansson** [comment]
What about `yarn cache clean`?

**Comment by An0nymous0** [comment]
@andyjansson I tried the yarn cache clean, but did not solve it.
I just downgrade caniuse-lite is not being given, do not downgrade on the error. So I think the bigger chance should be compatibility issues.

**Comment by Samllbox** [comment]
npm i caniuse-lite

**Comment by ai** [comment]
The problem was with npm servers, not the package

**Comment by spf1314as** [comment]
> The problem was with npm servers, not the package
how do you solve？

**Comment by ai** [comment]
@spf1314as wait 15 minutes and try again.

**Comment by liliangCS** [comment]
I have the same problem

**Comment by liliangCS** [comment]
(1.0.30001396 • Public • Published 3 hours ago)
I wonder if it is the reason that caniuse-lite was updated hours ago, because I didn't have any problems before

**Comment by liliangCS** [comment]
Now I am sure it is the compatibility problem of the new version, because I tried to lower the version of caniuse-lite, and the problem is perfectly solved.
