### ISSUE TITLE
Error: Cannot find module '../../data/browsers'

### ISSUE THREAD

**Issue by zhaowenjian** [ben-eb/caniuse-lite#39]
> todos@0.0.1 start D:\workspace\github\redux\examples\todos
> react-scripts start

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '../../data/browsers'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\workspace\github\redux\examples\todos\node_modules\caniuse-lite\dist\unpacker\browsers.js:6:35)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\workspace\github\redux\examples\todos\node_modules\caniuse-lite\dist\unpacker\agents.js:8:17)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)

**Comment by ai** [comment]
Seems like you have broken `node_modules`. Remove `nod_modules` and npm cache and install dependencies again.
